service: aws-serverless
frameworkVersion: '2 || 3'

plugins:
  - serverless-bundle

provider:
  name: aws
  runtime: nodejs18.x
  memorySize: 128
  region: us-east-1
  stage: ${opt:stage, 'dev'}
  lambdaHashingVersion: 20201221
  iamRoleStatements:
    - Effect: Allow
      Action:
        - dynamodb:PutItem
      Resource:
        - "arn:aws:dynamodb:us-east-1:754162583795:table/VideojuegosTable"

resources:
  Resources:
    VideojuegosTable:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: VideojuegosTable
        AttributeDefinitions:
          - AttributeName: id
            AttributeType: S
        KeySchema:
          - AttributeName: id
            KeyType: HASH
        BillingMode: PAY_PER_REQUEST
functions:
  crearVideojuego:
    handler: src/handlers/crearVideojuego.handler
    events:
      - httpApi:
          path: /videojuego
          method: POST


custom:
  bundle:
    linting: false