service: aws-serverless
frameworkVersion: '2 || 3'

plugins:
  - serverless-bundle

provider:
  name: aws
  runtime: nodejs18.x
  memorySize: 128
  region: us-east-1
  stage: ${opt:stage, 'dev'}
  lambdaHashingVersion: 20201221
  iamRoleStatements:
    - Effect: Allow
      Action:
        - dynamodb:PutItem
        - dynamodb:Scan
        - dynamodb:GetItem
        - dynamodb:DeleteItem
      Resource:
        - "arn:aws:dynamodb:us-east-1:754162583795:table/VideojuegosTable"

resources:
  Resources:
    VideojuegosTable:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: VideojuegosTable
        AttributeDefinitions:
          - AttributeName: id
            AttributeType: S
        KeySchema:
          - AttributeName: id
            KeyType: HASH
        BillingMode: PAY_PER_REQUEST
functions:
  crearVideojuego:
    handler: src/handlers/crearVideojuego.handler
    events:
      - httpApi:
          path: /videojuego
          method: POST
  listarVideojuego:
    handler: src/handlers/listarVideojuego.handler
    events:
      - httpApi:
          path: /videojuegos
          method: GET
  buscarVideojuego:
    handler: src/handlers/buscarVideojuego.handler
    events:
      - httpApi:
          path: /videojuego/{id}
          method: GET
  actualizarVideojuego:
    handler: src/handlers/actualizarVideojuego.handler
    events:
      - httpApi:
          path: /videojuegoU/{id}
          method: POST
  eliminarVideojuego:
    handler: src/handlers/eliminarVideojuego.handler
    events:
      - httpApi:
          path: /videojuegoE/{id}
          method: DELETE
custom:
  bundle:
    linting: false