service: aws-videojuegos
frameworkVersion: '2 || 3'

plugins:
  - serverless-bundle

provider:
  name: aws
  runtime: nodejs18.x
  memorySize: 128
  region: us-east-1
  stage: ${opt:stage, 'dev'}
  lambdaHashingVersion: 20201221
  iamRoleStatements:
    - Effect: Allow
      Action:
        - dynamodb:PutItem
        - dynamodb:Scan
        - dynamodb:GetItem
        - dynamodb:UpdateItem
        - dynamodb:DeleteItem
      Resource:
        - "arn:aws:dynamodb:us-east-1:754162583795:table/VideogamesTable"
      
resources:
  Resources:
    VideogamesTable:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: VideogamesTable
        AttributeDefinitions:
          - AttributeName: id
            AttributeType: S
        KeySchema:
          - AttributeName: id
            KeyType: HASH
        BillingMode: PAY_PER_REQUEST

functions:
  crearVideojuego:
    handler: src/handlers/createVideojuego.handler
    events:
      - http:
          path: /videogame
          method: post
          authorizer: ${self:custom.authorizer}
          cors: true
  getVideojuegos:
    handler: src/handlers/getVideojuegos.handler
    events:
      - http:
          path: /videogame
          method: GET
          authorizer: ${self:custom.authorizer}
          cors: true 
  getVideojuegoById:
    handler: src/handlers/getVideojuegoById.handler
    events:
      - http:
          path: /videogame/{id}
          method: GET
          authorizer: ${self:custom.authorizer}
          cors: true
  updateVideojuego:
    handler: src/handlers/updateVideojuego.handler
    events:
      - http:
          path: /videogame/{id}
          method: PUT
          authorizer: ${self:custom.authorizer}
          cors: true
  deleteVideojuego:
    handler: src/handlers/deleteVideojuego.handler
    events:
      - http:
          path: /videogame/{id}
          method: DELETE
          authorizer: ${self:custom.authorizer}
          cors: true
custom:
  authorizer: arn:aws:lambda:us-east-1:754162583795:function:aws-auth-dev-auth
  bundle:
    linting: false
